---
  - name: Updating
    apt: update_cache=yes
  - name: Insatlling apt-transport-https
    apt: name=apt-transport-https state=present
  - name: Installing ca-certificates
    apt: name=ca-certificates state=present

  - name: Adding APT-Key
    apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=present

  - name: Add an APT-source entry
    shell: echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
    args:
      creates: /etc/apt/sources.list.d/docker.list

  - name: Updating cache
    apt: update_cache=yes

  - shell: uname -r
    ignore_errors: yes
    register: uname_r

  - name: Installing linux-image-extra-{{ uname_r.stdout }}
    apt: name=linux-image-extra-{{ uname_r.stdout }} state=present

  - name: Installing linux-image-extra-virtual
    apt: name=linux-image-extra-virtual state=present

  - name: Instaling Docker Engine
    apt: name=docker-engine state=present

  - name: Installing Docker compose
    shell: curl -L "https://github.com/docker/compose/releases/download/1.8.0/docker-compose-$(uname -s)-$(uname -m)" > /usr/bin/docker-compose
    args:
      creates: /usr/bin/docker-compose

  - file: path=/usr/bin/docker-compose mode=0777
